services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mqtt-network

  web-api:
    build: ./web-api
    container_name: web-api
    environment:
      - FLASK_ENV
      - CLOUD_SERVICE_IP
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - mqtt-network

  web-client:
    build: ./web-client
    container_name: web-client
    environment:
      - NEXT_PUBLIC_CLOUD_SERVICE_IP=${CLOUD_SERVICE_IP}
    ports:
      - "3000:3000"
    networks:
      - mqtt-network

volumes:
  mysql_data:

networks:
  mqtt-network:
    driver: bridge
