### Get all moistures data
GET http://localhost:5000/api/humidity-data?sensor-id=1
Accept: application/json

### Get humidity chart data
GET http://localhost:5000/api/humidity-data/chart?sensor-id=1
Accept: application/json